[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 1000
solc-version = "0.8.24"

remappings = [
    "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
eth-mainnet = "https://ethereum-rpc.publicnode.com	